create table if not exists public.sobrenomes (
  nome character varying not null,
  constraint sobrenomes_pkey primary key (nome)
) TABLESPACE pg_default;

alter table public.sobrenomes enable row level security;

drop policy if exists "Enable read access for all users" on public.sobrenomes;

create policy "Enable read access for all users"
on public.sobrenomes
as PERMISSIVE
for SELECT
to public
using (
  true
);

create table if not exists public.localidades (
  cod integer not null,
  nome character varying not null,
  uf character varying not null,
  pop_local integer not null,
  constraint localidades_pkey primary key (cod)
) TABLESPACE pg_default;

alter table public.localidades enable row level security;

drop policy if exists "Enable read access for all users" on public.localidades;

create policy "Enable read access for all users"
on public.localidades
as PERMISSIVE
for SELECT
to public
using (
  true
);

create table if not exists public.frequencias (
  id bigint generated by default as identity not null,
  nome character varying not null,
  uf integer not null,
  frequencia integer not null,
  constraint frequencias_pkey primary key (id),
  constraint frequencias_nome_fkey foreign KEY (nome) references sobrenomes (nome),
  constraint frequencias_uf_fkey foreign KEY (uf) references localidades (cod)
) TABLESPACE pg_default;

alter table public.frequencias enable row level security;

drop policy if exists "Enable read access for all users" on public.frequencias;

create policy "Enable read access for all users"
on public.frequencias
as PERMISSIVE
for SELECT
to public
using (
  true
);