-- SOBRENOMES TABLE

create table if not exists public.sobrenomes (
  nome character varying not null,
  constraint sobrenomes_pkey primary key (nome)
) TABLESPACE pg_default;

alter table public.sobrenomes enable row level security;

drop policy if exists "Enable read access for all users" on public.sobrenomes;
create policy "Enable read access for all users"
on public.sobrenomes
as PERMISSIVE
for SELECT
to public
using (
  true
);

-- LOCALIDADES TABLE

create table if not exists public.localidades (
  cod integer not null,
  nome character varying not null,
  uf character varying not null,
  pop_local integer not null,
  constraint localidades_pkey primary key (cod)
) TABLESPACE pg_default;

alter table public.localidades enable row level security;

drop policy if exists "Enable read access for all users" on public.localidades;
create policy "Enable read access for all users"
on public.localidades
as PERMISSIVE
for SELECT
to public
using (
  true
);

-- FREQUENCIAS TABLE

create table if not exists public.frequencias (
  id bigint generated by default as identity not null,
  nome character varying not null,
  localidade integer not null,
  frequencia integer not null,
  constraint frequencias_pkey primary key (id),
  constraint frequencias_localidade_fkey foreign KEY (localidade) references localidades (cod),
  constraint frequencias_nome_fkey foreign KEY (nome) references sobrenomes (nome)
) TABLESPACE pg_default;

alter table public.frequencias enable row level security;

drop policy if exists "Enable read access for all users" on public.frequencias;
create policy "Enable read access for all users"
on public.frequencias
as PERMISSIVE
for SELECT
to public
using (
  true
);

-- FREQUENCIAS_ANALISE TABLE

create table if not exists public.frequencias_analise (
  id bigint generated by default as identity not null,
  nome character varying not null default ''::character varying,
  localidade integer not null,
  frequencia integer not null,
  share double precision not null,
  concentracao double precision not null,
  quociente_locacional double precision not null,
  constraint frequencias_analise_pkey primary key (id),
  constraint frequencias_analise_localidade_fkey foreign KEY (localidade) references localidades (cod),
  constraint frequencias_analise_nome_fkey foreign KEY (nome) references sobrenomes (nome)
) TABLESPACE pg_default;

alter table public.frequencias_analise enable row level security;

drop policy if exists "Enable read access for all users" on public.frequencias_analise;
create policy "Enable read access for all users"
on public.frequencias_analise
as PERMISSIVE
for SELECT
to public
using (
  true
);

create index if not exists idx_frequencias_analise_nome_localidade on public.frequencias_analise using btree (nome, localidade);
create index if not exists idx_frequencias_analise_localidade_quociente_locacional on public.frequencias_analise using btree (localidade, quociente_locacional);
